name: build

on:
  push:
    paths: 
      - .github/workflows/CI.yml
      - bin/**
      - kernel/**
      - lib/**
      - libc/**
      - linker/**
      - script/**
      - headers.sh
      - build.sh
      - mkiso.sh
env:
  READ_TOKEN: ${{ secrets.READ_PKG }} 
jobs:
  seraph:
    runs-on: ubuntu-latest
    container: echo $READ_TOKEN | docker login docker.pkg.github.com -u gk9339 --password-stdin; docker pull docker.pkg.github.com/gk9339/seraph/seraph-toolchain:latest
    steps:
    - name: build seraph
      run: ./build.sh
      
    - name: create iso
      run: ./mkiso.sh
      
    - name: Upload seraph.iso
      uses: actions/upload-artifact@v1
      with:
        name: seraph.iso
        path: seraph.iso
