name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  seraph:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: apt-update
      run: sudo apt-get update
    - name: apt-install
      run: sudo apt-get -y install bison flex libgmp3-dev libmpc-dev libmpfr-dev grub2 mtools
    - name: build
      run: ./build.sh
    - name: iso
      run: ./mkiso.sh
    - name: Upload seraph.iso
      uses: actions/upload-artifact@v1
      with:
        name: seraph.iso
        path: seraph.iso
